title: HDJekyll
email: roythomasstewart@gmail.com
description: A clean and minimalist theme for Jekyll.
baseurl: ""
url: "http://hd-jekyll.hdgenius.me"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

sass:
  sass_dir: _sass
  style: compressed
